version: 0.0

os: linux

files:
  - source: /
    destination: /var/www/html/myreactapp
    overwrite: true
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

file_exists_behaviour: OVERWRITE

hooks:  
  BeforeInstall:
    - location: scripts/server_clear.sh
      timeout: 100
      runas: root
  AfterInstall:
    - location: scripts/install_nginx.sh
      timeout: 300
      runas: root 
  ApplicationStop:
    - location: scripts/stop_nginx.sh
      timeout: 300
      runas: root    
  ApplicationStart:
    - location: scripts/start_nginx.sh
      timeout: 300
      runas: root
