version: 0.2

env:
  variables:
    RUNTIME_VERSION: "16"  # Replace with the desired Node.js version

phases:
  pre_build:
    commands:
      - sudo apt update
      - sudo apt install npm -y
      - sudo npm install
      - sudo npm update

  build:
    commands:
      - sudo npm run build

  post_build:
    commands:
      - echo "Build completed on `date`"

artifacts:
  files: 
    - public/**/*
    - src/**/*
    - package.json
    - appspec.yml
    - build/**/*
    - package-lock.json
    - scripts/**/*

cache:
  paths:
    - '/node_modules/**/*'


