version: 0.2

env:
  variables:
    RUNTIME_VERSION: "16"  # Replace with the desired Node.js version

phases:
  pre_build:
    commands:
      - npm install

  build:
    commands:
      - echo Installing NGINX
      - sudo apt-get update
      - sudo apt-get install nginx -y
      - npm run build

  post_build:
    commands:
      - echo "Build completed on `date`"

artifacts:
  files: 
    - 'elonfront/**/*'
  base-directory: 'build'

cache:
  paths:
    - 'node_modules/**/*'

